// <auto-generated />
namespace University.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change5Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change5Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201510121803436_change5Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
